### ISSUE TITLE
Use BToolBar instead of homegrown one

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/BePodder#16]

**Comment by janus2** [comment]
The problem here is which icons will we use?

**Comment by diversys** [comment]
Preferably using https://github.com/HaikuArchives/ZumisIcons.

**Comment by janus2** [comment]
I have uploaded ZumisIcons, there is no match for the buttons we need. Unless someone creates new icons for the purpose because there are similar buttons for subscriptions and for items (Their meaning is not very clear, but they are different).

**Comment by scottmc** [comment]
Make a list of the needed icons and we can make a task to create them.

**Comment by janus2** [comment]
Zumi made a lot of icons for this application but at the end, they used only the one present in the main windows (I have removed those present in the menus). There are those over the "Contents"  that work more as tabs. I don't know how this will translate to the main toolbar.

**Comment by janus2** [comment]
**RFC**
![native toolbar](https://user-images.githubusercontent.com/10423645/37362677-31872d54-26f6-11e8-8908-7ca8aa81afe2.png)

**Comment by scottmc** [comment]
i like the hand better.  Looking at the icons, i'm guessing it's Play, Download, Stop, and Delete.  If I'm wrong, then tool tips might be needed, and/or different icon(s).  What's up with the two blank column headings left of Title?  We see that same thing on Hare.

**Comment by KevinAdams05** [comment]
@scottmc Yes, you are correct about the function of the buttons. To be a little more specific, the “Stop” button stops the download process. The buttons have tooltips in the most current code on github.

The two columns left of Title are not blank when the list is populated. The one directly next to title displays an icon – paperclip if the file is not downloaded, a checkbox if the file is downloaded, and a down arrow when the download is in progress. 

The left most column seems to display a black square for New episodes. I’m not sure if this is supposed to be a square, or an image that did not get loaded. I’d have to look at the source again. Also this only seems to work on the version in HaikuDepot, and not when I build the latest code.

@janus2 I think this is a big improvement over what we have now. I do like the hand icon instead of the No symbol. The No symbol next to the X does not look very good. I think the border on the hand is a little too dark or thick. Other than that, the icons looks good to me. They are much more Haiku style than the current icons. Can you also update the ones below the Episode list? They look out of place now.

I’m not sure that a toolbar I the best control for these buttons… it seems a little unnatural to just have them floating above the list views. Unfortunately, I’m not sure what a better option would be. 

What do you think about the order of the buttons? I think Play, Delete, Download, Cancel would be a better order because Play and Delete are related activities, and Download and Cancel are related.

**Comment by janus2** [comment]
> What's up with the two blank column headings left of Title? We see that same thing on Hare.

@KevinAdams05 is right the second column is for the icon, the first is always present and is for the latch. Most applications don't use the latch so is empty. Sometimes with a hack, they draw other things in the space of the latch, but I don't like this practice.
